mlflow:
  tracking_uri: "file:./mlruns"
  registry_uri: "file:./mlruns"
  experiment_name: "/food_robotics/experiments"
  
experiments:
  vision_models: "/food_robotics/vision"
  motion_planning: "/food_robotics/motion"
  integration_tests: "/food_robotics/integration"

model_registry:
  staging_alias: "staging"
  production_alias: "production"
  latest_alias: "latest-model"

artifacts:
  location: "./mlartifacts"
  max_file_size: "100MB"
