name: MLOps Pipeline

on:
  push:
    branches: [ main ]

jobs:
  train-and-log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install mlflow scikit-learn pandas numpy
      - name: Run training
        run: |
          python src/train.py --data_path data/raw/raw.csv
